### ISSUE TITLE
Add repository and homepage fields into published package.json

### ISSUE THREAD

**Issue by Den-dp** [Nas3nmann/ngx-input-deep-linking#1]
In order to have a GitHub link to this repo on npm package page, you can add these fields into the package.json.

F.e. here is how it usually looks like in npm:
![image](https://user-images.githubusercontent.com/1770529/126983917-590395d7-19e0-493b-82dd-59326f2e21dd.png)

and here is how it's done:
https://github.com/angular/components/blob/24c35a41b267c18fe35eb4dd08cf25b91793967e/src/material/package.json#L5-L8

**Comment by Nas3nmann** [comment]
Hi @Den-dp thanks for pointing that out. I will take care of that today and publish a bugfix release.
